DROP TABLE ACCOUNT IF EXISTS;

CREATE TABLE ACCOUNT (
    ACC_ID INTEGER,
    ACC_FIRST_NAME VARCHAR(255),
    ACC_LAST_NAME VARCHAR(255),
    ACC_EMAIL VARCHAR(255)
);

INSERT INTO ACCOUNT VALUES (123, 'James', 'Strachan', 'TryGuessing@gmail.com');
INSERT INTO ACCOUNT VALUES (456, 'Claus', 'Ibsen', 'Noname@gmail.com');

